server:
  port: 7003
spring:
  application:
    name: eureka-server1
  security:
    user:
      roles: user
      password: ljq
      name: ljq
eureka:
  instance:
    hostname: eureka1
    prefer-ip-address: true
  server:
#      enable-self-preservation: false
      eviction-interval-timer-in-ms: 60000
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://ljq:ljq@eureka2:7002/eureka,http://ljq:ljq@eureka3:7003/eureka



