server:
  port: 8090

spring:
  application:
    name: cloudystudy-provider-config-git
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloudstudy?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
#  security:
#    user:
#      name: ljq
#      password: ljq
#      roles: user
mybatis:
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://ljq:ljq@eureka1:7004/eureka
  instance:
    instance-id: cloudystudy-provider-config-git
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90

info:
  app.name: ${spring.application.name}
  company.name: ljq
  build.artifactId: $project.artifactId$
  bulid.version: $project.version$

management:
  endpoints:
    web:
      exposure:
        include: '*'

