server:
  port: 7004
spring:
  application:
    name: eureka-server-git
  security:
    user:
      roles: user
      password: ljq
      name: ljq
eureka:
  instance:
    hostname: eureka-git
    prefer-ip-address: true
  server:
      enable-self-preservation: false
      eviction-interval-timer-in-ms: 60000
  client:
    fetch-registry: false
    register-with-eureka: false
#    service-url:
#      defaultZone: http://ljq:ljq@eureka1:7001/eureka,http://ljq:ljq@eureka2:7002/eureka



